
$\qquad$ $\qquad$$\qquad$  **TDA231/DIT370 Discrete Optimization: Home Assignment 1 -- Modelling and Solving with LPs** <br />
$\qquad$ $\qquad$$\qquad$                   **Grader: Divya** <br />
$\qquad$ $\qquad$$\qquad$                     **Due Date: 27th January** <br />
$\qquad$ $\qquad$$\qquad$                   **Submitted by: Name, Personal No., Email** <br />


---


General guidelines:
*   All solutions to theoretical and pratical problems must be submitted in this ipynb notebook, and equations wherever required, should be formatted using LaTeX math-mode.
*   All discussion regarding practical problems, along with solutions and plots should be specified in this notebook. All plots/results should be visible such that the notebook do not have to be run. But the code in the notebook should reproduce the plots/results if we choose to do so.
*   Your name, personal number and email address should be specified above.
*   All tables and other additional information should be included in this notebook.
*   Before submitting, make sure that your code can run on another computer. That all plots can show on another computer including all your writing. It is good to check if your code can run here: https://colab.research.google.com.


# Problem 1.

Consider the following LP problem:


\begin{array}
\mathcal{max}\quad 4x_1-2x_2+5x_3+6x_4+7x_5\\
\textrm{s.t} \\
2x_1 + 2x_2 - 4x_3 + 4x_4 + 8x_5 \leq 6\\
2x_1 + x_2 - 2x_3 - x_4 - 3x_5 \geq -1\\
5x_1 - 2x_2 + 4x_3 + 4x_4 + 2x_5 = 5\\
2x_1 - 2x_2 + 5x_3 + 3x_4 + x_5 \leq 4\\
\vec x \geq \vec 0
\end{array}

* (10 points) Use CVXOPT to solve the LP above. Submit your code, and print the solution vector and objective value.

In [9]:
import cvxpy as cp
import numpy as np

A = np.array([
             [2,2,-4,4,8], 
             [-2,-1,2,1,3],
             [5,-2,4,4,2],
             [-5,2,-4,-4,-2],
             [2,-2,5,3,1]
             ])

b = np.array([6,1,5,-5,4])

c = np.array([4,-2,5,6,7])

# Construct the problem.
x = cp.Variable(5)
constraints = [A @ x <= b, 0 <= x]
#print(constraints)
objective = cp.Maximize(c.T@x) 
prob = cp.Problem(objective, constraints)


result = prob.solve()
print(x.value)
print(result)

print(constraints[0].dual_value)


[ 6.27118644e-01  2.81355932e+00  1.54237288e+00 -5.09281400e-13
  6.61016949e-01]
9.22033898296506
[0.52542373 0.37288136 0.74119597 0.40221292 1.        ]


# Problem 2.

There are 4 space colonies, each of which  requires a certain number of plasma conduits. There are 3 starbases in the vicinity. Each of them has total number of conduits they can spare and supply to the colonies. For each pair of starbase and colony, there is an associated cost for sending a cargo ship  (each of which carries one plasma conduit), as shown in the table below:


\begin{array}{l|c|c|c|c|c} 
      & Triacus & New Berlin  & Strnad  & Vega  & supply\\ \hline
 Farpoint &   6 &  9 & 10 & 8 & 35\\
 Yorktown &  9 & 5 & 16 & 14 & 40\\
 Earhart & 12 &  7 & 13 & 9 & 50\\ \hline
    demand & 20 &30&30&45& \left(\sum=125\right) \\ 
\end{array}

Your goal is to supply the colonies the plasma conduits they need, at minimum cost.


* (5 points) Consider the general *transportation problem*: where there are $\bf{n}$ colonies and $\bf{m}$ bases and the costs are given by a $\bf{m} \times \bf{n}$ matrix $\mathcal{C}$, demand and supply are given by arrays $\bf{d}$ and $\bf{s}$ respectively. Formulate a LP to solve the problem.

* (3 points) Code the LP in CVXOPT, input the data for the space colonies manually and use CVXOPT to solve the LP. Submit your code and write down the solution and objective.

* (2 points) Use CVXOPT to show what  the  effect  on the model and the optimal solution would be if each of the starbases could supply five more conduits.

In [29]:
x = cp.Variable(12) # one variable for each way/edge
'''
[0] = farpoint - triacus
'''
#x = [1,2,3,4,5,6,7,8,9,10,11,12]

#(-(4*x[0] - 2*x[1] + 5*x[2] + 6*x[3] + 7*x[4]), [c1, c2, c3, c4, cx])

'''
A = [[6, 9, 10, 8],
     [9, 5, 16, 14],
     [12, 7, 13, 9]]
'''

A = [6, 9, 10, 8,
     9, 5, 16, 14,
     12, 7, 13, 9]

#t = A @ x
print(t)

objective = cp.Minimize(A@x)

constraints = [0 <= x]


prob = cp.Problem(objective, constraints)
prob.solve()
print(x.value)

#min -----> A@x

#b:
 #   A[1,:]@x[1,:] <= 35
    
  #  A[:, 1]@[:, 1] >= 20

#A[:,0]
#A[1,:]

[ 6.  9. 10.  8.  9.  5. 16. 14. 12.  7. 13.  9.] @ var284


ValueError: The 'minimize' objective must resolve to a scalar.

# Question 3 (Not to be turned in).
Use CVXOPT to model and solve the other examples in the textbook (sections 2.1 -- 2.6).

In [1]:
import cvxpy as cp
import numpy as np

# Problem data
A = np.array([[35,0.5,0.5], 
             [60,300,10],
             [30,20,10]])
b = np.array([0.5,15,4])

# Construct the problem.
x = cp.Variable(3)
print(x.value)
objective = cp.Minimize(cp.sum_squares(A@x - b))
constraints = [0 <= x]
prob = cp.Problem(objective, constraints)

# The optimal objective value is returned by `prob.solve()`.
result = prob.solve()
# The optimal value for x is stored in `x.value`.
print(x.value)
# The optimal Lagrange multiplier for a constraint is stored in
# `constraint.dual_value`.
print(constraints[0].dual_value)

None
[0.00952634 0.03826503 0.2948909 ]
[0. 0. 0.]


In [14]:
#test 

x = np.array([1,2,3])
c = [0 <= x]
print(c)
print(x)

[array([ True,  True,  True])]
[1 2 3]
