
$\qquad$ $\qquad$$\qquad$  **TDA231/DIT370 Discrete Optimization: Home Assignment 4 -- SDP and Maxcut** <br />
$\qquad$ $\qquad$$\qquad$                   **Grader: Divya** <br />
$\qquad$ $\qquad$$\qquad$                     **Due Date: 15th March** <br />
$\qquad$ $\qquad$$\qquad$                   **Submitted by:   Julia Molin, 950322-4124, mojulia@student.chalmers.se** <br />$\qquad$ $\qquad$$\qquad$$\qquad$$\qquad$$\quad$ **Ludwig Hultqvist, 970917-0071, ludhul@student.chalmers.se**<br />

---


General guidelines:
*   All solutions to theoretical and pratical problems must be submitted in this ipynb notebook, and equations wherever required, should be formatted using LaTeX math-mode.
*   All discussion regarding practical problems, along with solutions and plots should be specified in this notebook. All plots/results should be visible such that the notebook do not have to be run. But the code in the notebook should reproduce the plots/results if we choose to do so.
*   Your name, personal number and email address should be specified above.
*   All tables and other additional information should be included in this notebook.
*   Before submitting, make sure that your code can run on another computer. That all plots can show on another computer including all your writing. It is good to check if your code can run here: https://colab.research.google.com.


# Question 1.

Consider the triangle graph i.e, three vertices all connected pairwise (unweighted, so each edge has weight $1$).

* a. Write the $+1/-1$ labelling corresponding to a maximum cut and give the value of the cut.
* b. Write the SDP relaxation of the MAXCUT problem for this specific graph: write the program explicitly without using summation signs, with the variables corresponding to a $3 \times 3$ matrix, $X_{1,1,}, X_{1,2}, \cdots$.
* c. Solve the SDP by manual calculation (not using a SDP solver). (HINT: Use symmetry and then argue about when the matrix with $1$ as diagonal elements and $\alpha$ in other positions is psd.)
* d. Produce the vector labelling corresponding to the optimal solution of the SDP in (c). (HINT: for what angle is $\cos \theta = -1/2$?)
* e. What is the expected value of the cut produced by rounding using the vector labels and a random hyperlane? Give a short justification.



**1a)**

Let $G = (V, E)$ be the fully connected undirected triangle graph with:

$$
V = \{x_1, x_2, x_3\} \\
E = \{e_1 = (x_1, x_2), e_2 = (x_1, x_3), e_3 = (x_2, x_3)\} \\
w_e = 1     \ \ \ \   \forall e \in E
$$

Since we have 3 vertices, there's only 3 possible partitions (cuts). No matter which of these we chose, the cut will always be crossing two edges. Since all edges has equal weight, we can choose the partition arbitrarly as below:

The $+1/-1$ labelling of a maximum cut of G is then given as $x_1 = -1$ and $x_2 = x_3 = 1$. The max cut value $z^*$ is hence 2, computed as:

$$
z^* = 1(\frac{1-x_1x_2}{2}) + 1(\frac{1-x_1x_3}{2}) + 1(\frac{1-x_2x_3}{2}) = \frac{1}{2}(2 + 2 + 0) = 2
$$

---

**1b)**

The MAXCUT problem of G is defined as the following optimization problem in a simplified form without summation signs.

$$
\begin{alignat*}{2}
\max \quad & \frac{1}{2}(1-x_1x_2) + \frac{1}{2}(1-x_1x_3) + \frac{1}{2}(1-x_2x_3) \\
\textrm{s.t} \quad 
&x_1, x_2, x_3 \in \{-1, 1\} \\
\end{alignat*}
$$

By introducing vectors $\{v_1, v_2, v_3 \in \mathbb{R} : \lvert\lvert v \lvert\lvert = 1\}$ for the vertices $x_1, x_2, x_3$, a $3 \times 3$ positive semidefinite matrix of constrains $X$ can be introduced, as below, where every element $X_{ij} = v_i^Tv_j$. Using $X$, the SDP relaxation of the MAXCUT problem is expressed as following, where the objective function and constraints are linear in terms of $X_{ij}$.

$$ 
X =
\begin{bmatrix}
X_{11} & X_{12} & X_{13} \\
X_{21} & X_{22} & X_{23} \\
X_{31} & X_{32} & X_{33} \\
\end{bmatrix}
$$

$$
\begin{alignat*}{2}
\max \quad &
\frac{1}{2}(1 - X_{11}) + 
\frac{1}{2}(1 - X_{12}) + 
\frac{1}{2}(1 - X_{13}) + 
\frac{1}{2}(1 - X_{21}) + 
\frac{1}{2}(1 - X_{22}) + 
\frac{1}{2}(1 - X_{23}) +
\frac{1}{2}(1 - X_{31}) +
\frac{1}{2}(1 - X_{32}) + 
\frac{1}{2}(1 - X_{33}) \\
\textrm{s.t} \quad 
&X_{ii} = 1 \\
&X \succeq 0
\end{alignat*}
$$

Per definition, the matrix $X$ is symmetric, i.e. $X_{ij} = X_{ji}$ for all $i,j$, and every diagonal element $X_{ii} = 1$, $X$. $X$ can hence be expressed as following. Using the new expression of $X$, the objective function of the SDP relaxation is simplified.

$$ X =
\begin{bmatrix}
1 & X_{12} & X_{13} \\
X_{12} & 1 & X_{23} \\
X_{13} & X_{23} & 1 \\
\end{bmatrix}
$$

$$
\frac{1}{2}(1 - X_{11}) + 
\frac{1}{2}(1 - X_{12}) + 
\frac{1}{2}(1 - X_{13}) + 
\frac{1}{2}(1 - X_{21}) + 
\frac{1}{2}(1 - X_{22}) + 
\frac{1}{2}(1 - X_{23}) +
\frac{1}{2}(1 - X_{31}) +
\frac{1}{2}(1 - X_{32}) + 
\frac{1}{2}(1 - X_{33}) \\
= \frac{1}{2} (
(1 - 1) + 
(1 - X_{12}) + 
(1 - X_{13}) + 
(1 - X_{12}) + 
(1 - 1) + 
(1 - X_{23}) +
(1 - X_{13}) +
(1 - X_{23}) + 
(1 - 1) )\\
= \frac{2}{2} (
(1 - X_{12}) +
(1 - X_{13}) +
(1 - X_{23}) ) \\
= 3 - X_{12} - X_{13} - X_{23}
$$

With the simplified objective function, the SDP relaxation is finally expressed as following.

$$
\begin{alignat*}{2}
\max \quad & 3 - X_{12} - X_{13} - X_{23}\\
\textrm{s.t} \quad 
&X \succeq 0
\end{alignat*}
$$

---

**1c)**

Prove property of SDP

Matrix X is positive semidefinite if it holds for Cholesky decomposition:

$$
LL^T = X \implies X \succeq 0, \ \ \  \text{for any}
$$

...
fattar inte hur vi ska göra 

---

**1d)**

Use solution from c) to get vectors

---

**1e)**




# Question 2.


* a. Implement the SDP relaxation for MAXCUT in CVXPY (https://www.cvxpy.org), see (https://www.cvxpy.org/examples/basic/sdp.html). (Unfortunately  the API for SDP in CVXOPT is not very convenient, so we are forced to use CVXPY. The best way if you have installation issues would be to use Google Colab, there you can directly start using it.)
* b. Solve the SDP in the previous problem using (a).
* c. Solve the SDP and give the MAXCUT value for for the random graph $G(100, 0,1)$. Give the approximation ratio of your solution to the optimal max-cut value.
* d. Solve the SDP and give the MAXCUT value for the planted partition graph 'G' given below. Give the approximation ratio.

### Steps for implementing SDP for Maxcut

#### Formulate the Maxcut problem as SDP (recall lecture or refer to reference book [GM] in syllabus section)

####  Once you obtain 'X' (the solution positive-semi-definite matrix from SDP, you may use Cholesky decomposition to get the solution unit-vectors, stacked as column vectors in 'U')

```python
Xnew = X.value
eigs = np.linalg.eigh(Xnew)[0]
if np.min(eigs) < 0:
  Xnew = Xnew + (1.00001 * abs(min(eigs)) * np.identity(n_nodes))
elif np.min(eigs) == 0:
  Xnew = Xnew + 0.0000001 * np.identity(n_nodes)
U = np.linalg.cholesky(Xnew).T
```

#### Round the unit-vectors to appropriate partition as explained in [GM] or class.

**2a)** 

The SDP problem for arbitrary graphs can be specified as the following sum. However, to specify in a more CVXPY-friendly way, we can instead express the problem as the trace of the following matrix multiplication. Here, **W** is the matrix of edge-weights from the given graph while **1** is the matrix of 1's as every element. Using this definition, the method for computing Maxcuts are given below.

$$
z* = max \ \sum_{i,j} w_{i,j} \ \frac{1- X_{i,j}}{2} \ \ = \frac{1}{2}trace \ (\mathbf{W}(\mathbf{1}- \mathbf{X}))
$$

In [105]:
import cvxpy as cp
import numpy as np


def max_cut(G, print_variables=False):
    '''
    method for computing max cut of a given graph G
    set print_variables to true for debugging
    '''
    # matrix of edge-weights / 2
    W = G / 2
    
    # PSD matrix of variables
    X = cp.Variable(G.shape, symmetric=True)
    
    # SDP relaxation objective function and constraints
    objective = cp.Maximize(cp.trace(W @ (1 - X)))
    constraints = [X >> 0, cp.diag(X) == np.ones(G.shape[0])]
    
    # SDP relaxation solution and variables
    # divide by two since every X_ij is counted twice
    z = cp.Problem(objective, constraints).solve() / 2
    print("SDP relaxation optimal value: ", z)
    if print_variables:
        print("SDP relaxation optimal variables:\n", X.value)
    
    # Cholesky decomposition
    U = X.value
    I = np.identity(G.shape[0])
    eigs = np.linalg.eigh(U)[0]
    if np.min(eigs) < 0:
        U += 1.00001 * abs(min(eigs)) * I
    elif np.min(eigs) == 0:
        U += 0.0000001 * I
    U = np.linalg.cholesky(U).T
    
    # unit vectors of of SDP relaxation
    if print_variables:
        print("SDP relaxation unit vectors:\n", U)
    
    # uniformly chosen random vector
    q = np.random.rand(G.shape[0]).T
    q = q / np.linalg.norm(q)
    
    # rounded SDP relaxation solution and variables
    x = [1 if v >= 0 else -1 for v in np.dot(q, U)]
    # divide by 2 since every X_ij is counted twice
    y = sum(w * (1 - x[i]*x[j]) for (i, j), w in np.ndenumerate(W)) / 2
    print("SDP relaxation rounded optimal value: ", y)
    if print_variables:
        print("SDP relaxation rounded optimal variables:\n", x)
    
    # approximation ratio of SDP solution
    print("SDP optimal approximation ratio: ", y / z)


**2b)**

In [106]:
# fully connected triangle matrix
triangle = np.array([[0, 1, 1], 
                    [1, 0, 1], 
                    [1, 1, 0]])

# compute SDP solution
max_cut(triangle, print_variables=True)

SDP relaxation optimal value:  2.2499999998619593
SDP relaxation optimal variables:
 [[ 1.  -0.5 -0.5]
 [-0.5  1.  -0.5]
 [-0.5 -0.5  1. ]]
SDP relaxation unit vectors:
 [[ 1.00000000e+00 -5.00000000e-01 -5.00000000e-01]
 [ 0.00000000e+00  8.66025404e-01 -8.66025404e-01]
 [ 0.00000000e+00  0.00000000e+00  2.18066243e-05]]
SDP relaxation rounded optimal value:  2.0
SDP relaxation rounded optimal variables:
 [1, 1, -1]
SDP optimal approximation ratio:  0.8888888889434234


**2c)**

In [107]:
# random graph from G(100, 0, 1)
graph = np.loadtxt('../Lab2/graph.txt')

# compute SDP solution
max_cut(graph)

SDP relaxation optimal value:  368.26560649626316
SDP relaxation rounded optimal value:  335.0
SDP optimal approximation ratio:  0.9096695268049673


**2d)**

In [108]:
# planted partition graph given in assignment
adj_mat = np.array([[   0.  , 2., 1000.  ,  2. , 1000.  ,  2.  ,  2. ,1000.  ,  2.  ,  2.],
                    [ 2.  ,  0. ,1000.  ,  2., 1000.  ,  2.  ,  2. ,1000.  ,  2.  ,  2.],
                    [1000. , 1000.  ,  0. ,1000. ,   2. ,1000., 1000. ,   2. ,1000., 1000.],
                    [   2.  ,  2. ,1000.  ,  0. ,1000.  ,  2. ,   2., 1000.  ,  2.  ,  2.],
                    [1000., 1000.  ,  2. ,1000. ,   0., 1000. ,1000.  ,  2. ,1000. ,1000.],
                    [   2.  ,  2., 1000.  ,  2., 1000. ,   0. ,   2., 1000. ,   2. ,   2.],
                    [   2.  ,  2. ,1000.  ,  2. ,1000. ,   2. ,   0., 1000. ,   2. ,   2.],
                    [1000.  ,1000.,    2. ,1000.,    2., 1000., 1000.,    0., 1000., 1000.],
                    [   2. ,   2. ,1000. ,   2. ,1000. ,   2. ,   2., 1000.,    0.,    2.],
                    [   2. ,   2. ,1000. ,   2. ,1000. ,   2. ,   2., 1000.,    2.,    0.]])

max_cut(adj_mat)

SDP relaxation optimal value:  20999.997487426495
SDP relaxation rounded optimal value:  21000.0
SDP optimal approximation ratio:  1.0000001196463717
